### ISSUE TITLE
How to add normal openid ?

### ISSUE THREAD

**Issue by reutopiaer** [alixandru/q2a-open-login#50]
just like: <img src="https://www.dokuwiki.org/_media/plugin:openid.png?w=300&tok=7b154e">

**Comment by alixandru** [comment]
If your OpenID provider URL is always the same (not provided by the user) you can create a new class and place it in `Providers` folder. Look at `Yahoo.php` for an example. 
Otherwise, see the HybridAuth documentation page on how you can do this: http://hybridauth.sourceforge.net/userguide/IDProvider_info_OpenID.html

**Comment by reutopiaer** [comment]
@alixandru Thanks a lot! 

But is anyone can add normal openid to plugins options panel? Just like Yahho.php. I

I have try the exampe at IDProvider_info_OpenID.html,and get  PHP Fatal error:  Uncaught exception 'Exception' with message 'Authentication failed. Invalid request received!'   thrown in qa-plugin/open-login/Hybrid/Auth.php on line 150

**Comment by alixandru** [comment]
If you create a file and place it in Providers folder then the script will detect it and add it to the options panel in Q2A admin. The name of the file (w/o .php extension) will be used as the service name displayed in the page).

As for your error, please check the openid url and the credentials. You might find more info at HybridAuth or LightOpenID, on which this plugin is based.
