### ISSUE TITLE
cannot modify headers info....

### ISSUE THREAD

**Issue by gautamshelley** [alixandru/q2a-open-login#61]
as i  am enabling the enable facebook and show headers button I get an error on my admin 

::Warning: Cannot modify header information - headers already sent by (output started at G:\PleskVhosts\pantnagarworld.com\httpdocs\qa-plugin\q2a-open-login-master\qa-open-page-logins.php:780) in G:\PleskVhosts\pantnagarworld.com\httpdocs\qa-include\qa-page.php on line 220::

**Comment by alixandru** [comment]
Make sure there is a files called providers.php in your plugin directory. You can rename providers-sample.php to providers.php. Also, very important, make sure that file is writable by the webserver process!
As stated in the docs, the plugin must be able to write to this file, otherwise things won't work at all.

**Comment by gautamshelley** [comment]
if i'm running the plugin on my localhost it is working fine and showing the fb login box.....but as i updated it to my server it shows the error......

**Comment by alixandru** [comment]
What are the parameters from the URL of the return page? Any error code?
